### ISSUE TITLE
inProgress not set to false

### ISSUE THREAD

**Issue by KunWuLuan** [kubewharf/godel-scheduler#32]
https://github.com/kubewharf/godel-scheduler/blob/80119ac0c3f9ddcc897c3659261d0bf3ea3688e0/pkg/binder/godel_binder.go#L457-L472

**Comment by KunWuLuan** [comment]
It seems `inProgress` is always true even if time.Now().After(ddl) return true. Is this as expected?

**Comment by NickrenREN** [comment]
@XinyiSong PTAL
