### ISSUE TITLE
Missing Pod Group State Machine Graph

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [kubewharf/godel-scheduler#55]
When I walked through the repo, I found the graph is missing. See [pod_group_state_machine.md](https://github.com/kubewharf/godel-scheduler/blob/main/pkg/binder/controller/pod_group_state_machine.md).

**Comment by binacs** [comment]
thanks for your feedback, we will fix it in [this pr](https://github.com/kubewharf/godel-scheduler/pull/56).
