### ISSUE TITLE
Some questions about the performance

### ISSUE THREAD

**Issue by xieqingxing** [kubewharf/godel-scheduler#59]
In this article(https://developer.volcengine.com/articles/7379480082940690442), it is mentioned that a single-shard Godel scheduler can achieve  2500+ Pods/s. I would like to know in what scenario this performance data was obtained. Does "single-shard" refer to only the default cluster, or does it involve multiple subcluster？

Thanks for your answer!

**Comment by binacs** [comment]
Single-shard scheduler in 10k nodes in a cluster, no multiple subcluster workflows.

**Comment by binacs** [comment]
Single-shard scheduler in a 10k nodes cluster, without multiple sub-cluster workflows.

**Comment by NickrenREN** [comment]
“single-shard" has nothing to do with cluster (sub-cluster or cluster scale), it means "only one scheduler instance" (godel supports multiple scheduler instances working in parallel).

**Comment by NickrenREN** [comment]
closing if no more questions
