### ISSUE TITLE
【编译构建镜像失败】

### ISSUE THREAD

**Issue by qq547475331** [kubewharf/godel-scheduler#60]
[root@master1 godel-scheduler-main]# ls -la
总用量 188
drwxr-xr-x  14 root root   4096 8月   1 17:14 .
dr-xr-x---. 35 root root   4096 8月   1 17:14 ..
drwxr-xr-x   5 root root     55 7月  15 20:01 cmd
-rw-r--r--   1 root root   3289 7月  15 20:01 CODE_OF_CONDUCT.md
-rw-r--r--   1 root root    773 7月  15 20:01 CODEOWNERS
-rw-r--r--   1 root root   5383 7月  15 20:01 CONTRIBUTING.md
drwxr-xr-x   2 root root     36 7月  15 20:01 docker
drwxr-xr-x   5 root root     57 7月  15 20:01 docs
drwxr-xr-x   2 root root     29 7月  15 20:01 e2e-cluster
drwxr-xr-x   3 root root     23 7月  15 20:01 .github
-rw-r--r--   1 root root    569 7月  15 20:01 .gitignore
-rw-r--r--   1 root root   1592 7月  15 20:01 .golangci.yml
-rw-r--r--   1 root root   6764 7月  15 20:01 go.mod
-rw-r--r--   1 root root 102703 7月  15 20:01 go.sum
drwxr-xr-x   5 root root   4096 7月  15 20:01 hack
-rw-r--r--   1 root root  11357 7月  15 20:01 LICENSE
-rw-r--r--   1 root root   7349 7月  15 20:01 .licenseignore
drwxr-xr-x   3 root root     20 7月  15 20:01 LICENSES
-rw-r--r--   1 root root   6929 7月  15 20:01 Makefile
-rw-r--r--   1 root root   2328 7月  15 20:01 Makefile.expansion
drwxr-xr-x   5 root root     69 7月  15 20:01 manifests
drwxr-xr-x  15 root root    205 7月  15 20:01 pkg
-rw-r--r--   1 root root   2896 7月  15 20:01 README.md
drwxr-xr-x   5 root root     44 7月  15 20:01 test
drwxr-xr-x   2 root root     22 7月  15 20:01 tools
drwxr-xr-x  12 root root    223 7月  15 20:01 vendor
[root@master1 godel-scheduler-main]#
[root@master1 godel-scheduler-main]#
[root@master1 godel-scheduler-main]# make local-up
find: ‘build’: 没有那个文件或目录
dirname: 缺少操作数
Try 'dirname --help' for more information.
./hack/make-rules/build-images.sh
Building docker image(s) for ...
Deleted Containers:
07ba7ba9e718770d50045a472961596ed6a75c71cc7ac1c144e77a019b39c994

Total reclaimed space: 0B
Total reclaimed space: 0B
fatal: Not a git repository (or any of the parent directories): .git
make: *** [docker-images] 错误 128
[root@master1 godel-scheduler-main]# make docker-images
find: ‘build’: 没有那个文件或目录
dirname: 缺少操作数
Try 'dirname --help' for more information.
./hack/make-rules/build-images.sh
Building docker image(s) for ...
Total reclaimed space: 0B
Total reclaimed space: 0B
fatal: Not a git repository (or any of the parent directories): .git
make: *** [docker-images] 错误 128
[root@master1 godel-scheduler-main]#

**Comment by qq547475331** [comment]
修改./hack/make-rules/build-images.sh脚本后可以构建docker镜像了

#!/bin/bash  
  
# error on exit  
set -e  
  
# Main of the script  
DOCKERFILE_DIR="docker/"  
LOCAL_DOCKERFILE="godel-local.Dockerfile"  
  
echo "Building docker image(s)..."  
  
docker container prune -f || true;  
docker image prune -f || true  
  
function cleanup_godel_images() {  
  for i in $(docker images | grep "${1}" | awk "{print \$3}");  
  do  
    docker rmi "$i" -f;  
  done  
}  
  
build_image() {  
  local file=${1}  
  REPO=$(basename "$file");  
  REPO=${REPO%.*};  
  
  # Check if we are in a Git repository  
  if [ -d ".git" ]; then  
    REV=$(git log --pretty=format:'%h' -n 1)  
    TAG="${REPO}:${REV}"  
  else  
    # Use a fixed tag if not in a Git repository  
    REV="non-git-commit"  
    TAG="${REPO}:${REV}"  
    echo "Warning: Building image with non-Git tag '${TAG}' because this is not a Git repository."  
  fi  
  
  cleanup_godel_images "${REPO}"  
  docker build -t "${TAG}" -f "$file" ./;  
  docker tag "${TAG}" "${REPO}:latest"  
}  
  
for file in $(find "$DOCKERFILE_DIR" -name *.Dockerfile);  
do  
  build_image "${file}"  
done;

**Comment by qq547475331** [comment]
#!/bin/bash  
  
# error on exit  
set -e  
  
# Main of the script  
DOCKERFILE_DIR="docker/"  
LOCAL_DOCKERFILE="godel-local.Dockerfile"  
  
echo "Building docker image(s)..."  
  
docker container prune -f || true;  
docker image prune -f || true  
  
function cleanup_godel_images() {  
  for i in $(docker images | grep "${1}" | awk "{print \$3}");  
  do  
    docker rmi "$i" -f;  
  done  
}  
  
build_image() {  
  local file=${1}  
  REPO=$(basename "$file");  
  REPO=${REPO%.*};  
  
  # Check if we are in a Git repository  
  if [ -d ".git" ]; then  
    REV=$(git log --pretty=format:'%h' -n 1)  
    TAG="${REPO}:${REV}"  
  else  
    # Use a fixed tag if not in a Git repository  
    REV="non-git-commit"  
    TAG="${REPO}:${REV}"  
    echo "Warning: Building image with non-Git tag '${TAG}' because this is not a Git repository."  
  fi  
  
  cleanup_godel_images "${REPO}"  
  docker build -t "${TAG}" -f "$file" ./;  
  docker tag "${TAG}" "${REPO}:latest"  
}  
  
for file in $(find "$DOCKERFILE_DIR" -name *.Dockerfile);  
do  
  build_image "${file}"  
done;

**Comment by qq547475331** [comment]
```
#!/bin/bash  
  
# error on exit  
set -e  
  
# Main of the script  
DOCKERFILE_DIR="docker/"  
LOCAL_DOCKERFILE="godel-local.Dockerfile"  
  
echo "Building docker image(s)..."  
  
docker container prune -f || true;  
docker image prune -f || true  
  
function cleanup_godel_images() {  
  for i in $(docker images | grep "${1}" | awk "{print \$3}");  
  do  
    docker rmi "$i" -f;  
  done  
}  
  
build_image() {  
  local file=${1}  
  REPO=$(basename "$file");  
  REPO=${REPO%.*};  
  
  # Check if we are in a Git repository  
  if [ -d ".git" ]; then  
    REV=$(git log --pretty=format:'%h' -n 1)  
    TAG="${REPO}:${REV}"  
  else  
    # Use a fixed tag if not in a Git repository  
    REV="non-git-commit"  
    TAG="${REPO}:${REV}"  
    echo "Warning: Building image with non-Git tag '${TAG}' because this is not a Git repository."  
  fi  
  
  cleanup_godel_images "${REPO}"  
  docker build -t "${TAG}" -f "$file" ./;  
  docker tag "${TAG}" "${REPO}:latest"  
}  
  
for file in $(find "$DOCKERFILE_DIR" -name *.Dockerfile);  
do  
  build_image "${file}"  
done;
```

**Comment by NickrenREN** [comment]
cc @yuey002
